sudo: required
services:
 - docker
 
 
before_install:
 - docker build -t rsharma/docker-reat -f Dockerfile.dev .
 
script:
 - docker run rsharma/docker-reat npm run test -- --coverage
 
 deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-798677290729"
  bucket_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
   secure: "$AWS_SECRET_KEY"